### ISSUE TITLE
Separate check and correction action

### ISSUE THREAD

**Issue by jtyr** [MindPointGroup/RHEL6-STIG#14]
I like this role but I would appreciate if it would be possible to separate the check from the correction action. That would allow us to skip certain correction actions if the files touched by the action are managed by other Ansible role. Then we could use `ansible-playbook --skip-tags="V-38653-action" site.yaml` to run all the STIG checks and correction actions but the V-38653 action.

**Comment by defionscode** [comment]
The challenge here is that there isn't always a task that checks and then a check that remediates. For many components it's just Ansible being idempotent with a single task. Sure it could be done with __some__ tasks but it ultimately wouldn't work out for everything. If you are using some other role that messes with the same file then I would ultimately advise to remove that task from one of the roles so you simply don't have duplication to begin with. If I misunderstood something let me know.

**Comment by jtyr** [comment]
Please could you name a task for which you think it wouldn't be possible to create a check?

**Comment by defionscode** [comment]
I see what you mean, I didn't fully grasp what you meant initially. So yes for tasks where the source of identification and remediation occur in the same task  (ie something that only leverages a single module call like `V-38457`) we could theoretically them all into check and action tasks. 

My initial opinion is to not be in favor of this due to the increased workload for what I'm perceiving, initially anyways, to be a minimal gain. This is not a dogmatic opinion and am certainly open to further discussion (and keeping this issue open) and would want to get @shepdelacreme's take on this too.

**Comment by jtyr** [comment]
I think that it would be worth the work to split every task into a check task and a remediation task. I believe that the audience of this role will be very limited without this feature.

**Comment by defionscode** [comment]
I definitely understand where you're coming from. Thinking about it a bit more. Rather that splitting it off (or at least using those words) I think I'd be more in favor of adding (versus splitting) check tasks that don't interact with any of the logic that's already been built. This way you can run all of the things via check mode while cleverly using `always_run: yes` for all of the check related tasks; you'd be able to skip a rule but still be able to see the outcome of the check task(s). Thoughts?

**Comment by shepdelacreme** [comment]
It would be a fairly significant undertaking but might be worth it. I wanted to build a separate "audit" role that would simply run all the STIG checks similar to what openscap does. So maybe adding check tasks and incorporating them into the existing role is the way to go. I like the ```always_run: yes``` idea.

**Comment by jtyr** [comment]
I would definitely appreciate a role which would allow to run only checks without any remediation (audit mode).

**Comment by defionscode** [comment]
Adding this as an action item for the next release.

**Comment by samdoran** [comment]
After going down the path of adding discrete audit tasks, we have determined that the audit tasks are more of a distraction than a net benefit. We will be removing them unless the community decides otherwise.

See discussion [here](https://groups.google.com/forum/#!topic/ansible-lockdown/KxdtoeRuZM0).
