### ISSUE TITLE
error: "net.ipv6.conf.default.accept_redirects" is an unknown key

### ISSUE THREAD

**Issue by bbaassssiiee** [MindPointGroup/RHEL6-STIG#55]
sysctl reload in rule V-38596 fails, but offending key introduced in rule V-38548.

**Comment by bbaassssiiee** [comment]
sysctl module has this option: 

- ignoreerrors
        Use this option to ignore errors about unknown keys.

**Comment by samdoran** [comment]
@bbaassssiiee I am able to duplicate this. It fails if IPv6 is disabled in the kernel since the key is then unknown.

The task doesn't fail if IPv6 is enabled at the time that it's disabled, since the kernel parameter is known. Since the test machine I am using has IPv6 enabled to start, I didn't see this error before. If you disable IPv6, reboot, disabling IPv6 completely, then it will fail.

I'll add two things to the task to fix this: 1) You suggestion of `ignoreerrors` and 2) a conditional checking the status of `rhel6stig_ipv6_required`. This variable existed early on as a way to toggle the IPv6 tasks on and off, but it has fallen out over several revisions. I'll put it back in to add another layer of control to the execution of these tasks.

**Comment by samdoran** [comment]
It seems that adding `ignoreerrors` to the `sysctl` module doesn't guarantee it won't fail. I would have to add `ignore_errors` to the task to get it working properly.

Skipping the task if `rhel6stig_ipv6_required` is `False` does solve this issue.

**Comment by bbaassssiiee** [comment]
Skipping 'virtual address space randomization' when 'ipv6 is disabled' does not make sense, it hides an issue in the implementation.

**Comment by bbaassssiiee** [comment]
when ipv6 is disabled net.ipv6.conf.default.accept_redirects should be removed from sysctl

**Comment by samdoran** [comment]
You are correct that skipping 'virtual address space randomization' when IPv6 is disabled doesn't make sense. What the fix does is skip the V-38548 task if IPv6 is disabled. It _does not_ skip the V-38596 task, which enables ASLR . But the issue was a key set in V-38548 _when IPv6 was disabled_ caused the subsequent task that disabled ASLR to fail. That is fixed.

To your second point that `net.ipv6.conf.default.accept_redirects` should be removed if IPv6 disabled, I'll have to do some more work to accomplish that. I would have to change the variable from a bool to a status, or possibly add some `set_fact` tasks. My assumption (for better or worse) was that it would never bet set and therefore not need removing. Also, if IPv6 is disabled, then the `sysctl.conf` settings related to IPv6 would have no effect anyway — but that does leave some cruft on the system. A better approach would be to make the task "clean up" if IPv6 support is toggled back and forth on a machine, but that was not on my mind at the time.

I belive this particual issues is resolved. I will open a new issue on the removal of `sysctl` settings if they are not necessary.

**Comment by bbaassssiiee** [comment]
The removal is outside the scope of RHEL6-STIG, however be aware that there can be unknown keys.

**Comment by samdoran** [comment]
@bbaassssiiee I believe the point is to add `ignoreerrers` to `sysctl` tasks, but do you feel we need to invest in ensuring `sysctl.conf` settings are _removed_ if no longer needed?

**Comment by bbaassssiiee** [comment]
sysctl: 
    ignoreerrors: yes

That is sufficient IMHO
